[versions]

kotlin = "1.6.10"
androidGradle = "7.3.0-alpha08"
androidCore = "1.6.0"
appcompat = "1.3.1"
material = "1.4.0"
compose = "1.1.0-alpha03"
composeActivity = "1.3.1"
lifecycle = "2.3.1"

[libraries]

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
android-material = { module = "com.google.android.material:material", version.ref = "material"}
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity"}
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

[bundles]

androidx-compose = [
    "androidx-compose-ui",
    "androidx-compose-material",
    "androidx-compose-uiTooling",
    "androidx-compose-activity"
]